### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by TsunokakeTaiki** [TsunokakeTaiki/furima-31694#10]
#自身のフリマアプリのURL
 https://furima-31694.herokuapp.com/

#Basic認証のIDとパスワード
ID:admin
パスワード:2222

#出品者用のメールアドレスとパスワード
mail:test2@mail.jp
pass:11111a

#購入者用のメールアドレスとパスワード
mail:test@mail.jp
pass:11111a

#購入用カードの番号・期限・セキュリティコード
No:4242424242424242
exp:3/23
cvc:123

**Comment by naru6117** [comment]
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/101110605-b21a8a00-361c-11eb-94f1-53bbac3fb082.png)

TsunokakeTaikiさん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
